#FROM python:3.9-slim
FROM python:3.9-buster

ARG USERNAME=python

RUN useradd -m $USERNAME

# install AWS CLI (requires groff, less, glibc)
RUN apt update && apt install zip groff less curl -y && rm -rf /var/lib/apt/lists/*
RUN curl -L https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/aws.zip; unzip /tmp/aws.zip; ./aws/install; rm /tmp/aws.zip

# change the username
RUN pip3 install --upgrade pip
RUN pip3 install streamlit httpx websockets pyjwt cryptography

# Required for Pyre
#RUN pip3 install pyre-check
#RUN pip3 install click click-log ipython==7.6.1 munch pygments SQLAlchemy ujson~=1.35 xxhash~=1.3.0 prompt-toolkit~=2.0.9 flask flask_cors flask_graphql graphene graphene_sqlalchemy
# End required for Pyre

COPY streamlit_app.py /home/${USERNAME}/

RUN chown -R ${USERNAME}.${USERNAME} /home/${USERNAME}/

USER $USERNAME

ENV PATH="${PATH}:/home/${USERNAME}/.local/bin"

WORKDIR /home/${USERNAME}/

ENTRYPOINT ["streamlit"]
CMD ["run", "streamlit_app.py"]
